name: mirror

on: push

env:
    MIRROR_URL: 'git@github.com:EpitechPromo2028/B-ASM-400-PAR-4-1-asmminilibc-gregor.sternat.git'

jobs:
    push_to_mirror:
        name: Push to mirror
        runs-on: ubuntu-latest

        if: github.repository != 'EpitechPromo2028/B-ASM-400-PAR-4-1-asmminilibc-gregor.sternat'
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Mirroring to the repository
              uses: pixta-dev/repository-mirroring-action@v1
              with:
                  ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
                  target_repo_url: ${{ env.MIRROR_URL }}
